### ISSUE TITLE
Error installing v0.5.1

### ISSUE THREAD

**Issue by horothesun** [bow-swift/homebrew-nef#1]
Hi all and thanks for this super useful tools!

Unfortunately, I'm getting the following error trying to install the latest version (0.5.1)

```
Error: nef: /usr/local/Homebrew/Library/Taps/bow-swift/homebrew-nef/nef.rb:4: syntax error, unexpected <<, expecting end
<<<<<<< HEAD
^~
/usr/local/Homebrew/Library/Taps/bow-swift/homebrew-nef/nef.rb:7: syntax error, unexpected ===, expecting end
=======
^~~
/usr/local/Homebrew/Library/Taps/bow-swift/homebrew-nef/nef.rb:10: syntax error, unexpected >>, expecting end
>>>>>>> Update nef.rb
^~
/usr/local/Homebrew/Library/Taps/bow-swift/homebrew-nef/nef.rb:36: syntax error, unexpected <<, expecting end
<<<<<<< HEAD
^~
/usr/local/Homebrew/Library/Taps/bow-swift/homebrew-nef/nef.rb:41: syntax error, unexpected ===, expecting end
=======
^~~
/usr/local/Homebrew/Library/Taps/bow-swift/homebrew-nef/nef.rb:46: syntax error, unexpected >>, expecting end
>>>>>>> Update nef.rb
^~
```

Am I missing something?

Thanks,
Nicola

**Comment by calvellido** [comment]
Weird, those messages (`<<<<<<< HEAD`) seems to be a repo merge pending to be completed :thinking: 

Could you please try the following:

```
brew uninstall nef
brew untap bow-swift/nef
brew tap bow-swift/nef
brew install nef
```

Maybe that way the local cloned repo gets updated correctly this time.

**Comment by truizlop** [comment]
I tried to reproduce it and everything works nicely for me. It seems you may have a version of the formula that is wrong for some reason. The steps that Juan provides above should work. In case they don't let us know and we will try to figure out what's happening.

**Comment by miguelangel-dev** [comment]
Internally Homebrew works like a repository, and as Tomas said, your local formulae version is wrong (I suppose it is the v0.5) and when you try to update it with the new one, it fails; it had a conflict in the upgrade process.

As my mate @calvellido suggest you, you only need to force the replacement of the formulae instead to update it.

```bash
brew uninstall nef
brew install nef
```

Keep us informed!

**Comment by horothesun** [comment]
It worked perfectly. 🙌
I just had to unlink the previously installed version as well with `brew unlink nef@0.3.2`.
Thanks a lot! 🙏
